// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230517195248_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.CityPrayerTimes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CityPrayerTimes");
                });

            modelBuilder.Entity("Domain.Models.DailyPrayerTimes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AsrHanafiTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AsrTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CityPrayerTimesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DhuhrTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FajrTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("IshaTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("MaghribTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SunriseTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityPrayerTimesId");

                    b.ToTable("DailyPrayerTimes");
                });

            modelBuilder.Entity("Domain.Models.DailyPrayerTimes", b =>
                {
                    b.HasOne("Domain.Models.CityPrayerTimes", null)
                        .WithMany("DailyPrayerTimesList")
                        .HasForeignKey("CityPrayerTimesId");
                });

            modelBuilder.Entity("Domain.Models.CityPrayerTimes", b =>
                {
                    b.Navigation("DailyPrayerTimesList");
                });
#pragma warning restore 612, 618
        }
    }
}
