name: Build, publish and deploy project to Web Deploy server

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: windows-latest

    env:
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore ./Web/Web.csproj --runtime win-x86

      - name: Build
        run: dotnet build ./Web/Web.csproj --configuration Release --runtime win-x86 --no-restore

      - name: Inject connection string
        shell: pwsh
        run: |
          $config = @{
            ConnectionStrings = @{
              DefaultConnection = $env:CONNECTION_STRING
            }
          } | ConvertTo-Json -Depth 10

          Set-Content -Path ./Web/appsettings.Production.json -Value $config

      - name: Publish
        run: >
          dotnet publish ./Web/Web.csproj
          --configuration Release
          --framework net8.0
          --output ./publish
          --runtime win-x86
          --self-contained true
          --no-restore
          -p:PublishTrimmed=false
          -p:PublishSingleFile=false

      - name: Show publish output size
        shell: pwsh
        run: |
          Write-Host "Total publish size:"
          Get-ChildItem ./publish -Recurse -File | Measure-Object -Property Length -Sum

          Write-Host "File count:"
          (Get-ChildItem ./publish -Recurse -File).Count

      - name: Deploy to Simply with Web Deploy
        uses: rasmusbuchholdt/simply-web-deploy@2.2.0
        with:
          website-name: salahtimes.dk
          server-computer-name: https://nt38.unoeuro.com:8172
          server-username: salahtimes.dk
          server-password: ${{ secrets.sERVER_PASSWORD }}
          source-path: '\publish\'
          target-delete: false
