name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish

      - name: Set Environment Variable
        run: echo "CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}" >> $GITHUB_ENV

      - name: Deploy to IIS
        run: |
          $msdeployPath = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          & $msdeployPath -verb:sync -source:contentPath="./publish" -dest:contentPath="salahtimes.dk",ComputerName="https://nt38.unoeuro.com:21/msdeploy.axd?site=salahtimes.dk",UserName="salahtimes.dk",Password="${{ secrets.DEPLOYMENT_PASSWORD }}",AuthType="Basic" -allowUntrusted
