name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      AdminErrorDetailsSecret: ${{ secrets.ADMIN_ERROR_DETAILS_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish Web
        run: dotnet publish ./Web/Web.csproj --configuration Release --no-build --output ./publish

      - name: Deploy to IIS
        uses: ChristopheLav/iis-deploy@v1.0.0
        with:
          website-name: 'http://salahtimes.dk'
          msdeploy-service-url: 'http://salahtimes.dk.nt38.unoeuro-server.com:8172'
          msdeploy-username: 'salahtimes.dk'
          msdeploy-password: '${{ secrets.DATABASE_PASSWORD }}'
          source-path: './publish'
